name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Linting
        run: |
          pip install flake8
          flake8

  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Variables
        id: set_variables
        run: |
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
          echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.set_variables.outputs.PIP_CACHE }}
            ${{ steps.set_variables.outputs.PDM_CACHE }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pdm use -f ${{ matrix.python-version }}
          pdm sync -d -G toc -G codehilite
      - name: Run Tests
        run: |
          pdm run -v pytest --cov=marko/ --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
